[package]
name = "nocastinator"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.75"
poise = "0.5.7"
shuttle-poise = "0.35.1"
shuttle-runtime = "0.35.1"
shuttle-secrets = "0.35.1"
tracing = "0.1.40"
tokio = "1.35"
